version: 1.0.{build}

install:
  - cmd: cmake --version
  - cmd: echo "Downloading biicode..."
  - ps: wget http://www.biicode.com/downloads/latest/win -OutFile bii-win.exe
  - cmd: bii-win.exe /VERYSILENT
  - cmd: set PATH=%PATH%;C:\Program Files (x86)\BiiCode\bii
  - cmd: bii -v
  - cmd: del bii-win.exe
  - cmd: set PATH=%PATH%;C:\MinGW\bin

before_build:
  - cmd: bii init -L
  - cmd: bii configure -G "MinGW Makefiles"
  - cmd: bii user %block_user% -p %secured_passwd%

build_script:
  - cmd: bii build

test_script:
  - cmd: cd bin
  - cmd: dir
  - cmd: Dani_MTB_continuous_integration_main.exe

deploy_script:
  - cmd: bii user %block_user% -p %secured_passwd%
  - if defined APPVEYOR_REPO_TAG_NAME set VERSION=%APPVEYOR_REPO_TAG_NAME%
  - if defined APPVEYOR_REPO_TAG_NAME bii publish -r --tag=STABLE --versiontag=%VERSION%
  - if not defined APPVEYOR_REPO_TAG_NAME bii publish -r

on_success:
  - ps: |
        $new_biiconf = get-content biicode.conf
        $orig_biiconf = get-content "$env:APPVEYOR_BUILD_FOLDER\biicode.conf"
        if (diff $new_biiconf $orig_biiconf){
           'different, updating biicode parents'
           git checkout "$env:APPVEYOR_REPO_BRANCH"
           git config --global core.autocrlf true
           git config --global credential.helper store
           Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
           git remote add neworigin "$env:github_repo"
           git config --global user.email "$env:github_email"
           git config --global user.name "$env:github_user"
           git add biicode.conf
           git commit -m "Updated biicode parents [skip ci]"
           git push neworigin "$env:APPVEYOR_REPO_BRANCH"
           }Write-Host "Updated biicode parents" else {
            'equal, no parents update needed'
          }

environment:
  block_user:
    "Dani_MTB"
  secured_passwd:
    secure: Xs9AudM/J5BVLFyYfvrTOw==
  access_token:
    secure: g6d47EtmEgEwlRp03bgzT24fAzt3wYuAP8cz7wnx1zqwJcZrU317la2wZ0a6rtsU
  github_user:
    "danimtb"
  github_email:
    "danimanzaneque@gmail.com"
  github_repo:
    "git@github.com:danimtb/continuous_integration.git"