version: 1.0.{build}

install:
  - cmd: cinst cmake -version 3.0.2 -y
  - cmd: cmake --version
  - cmd: echo "Downloading biicode..."
  - ps: wget http://www.biicode.com/downloads/latest/win -OutFile bii-win.exe
  - cmd: bii-win.exe /VERYSILENT
  - cmd: set PATH=%PATH%;C:\Program Files (x86)\BiiCode\bii
  - cmd: bii -v
  - cmd: del bii-win.exe

before_build:
  - cmd: bii init -L
  - cmd: bii configure -G "Visual Studio 12"
  - cmd: bii user %block_user% -p %secured_passwd%

build_script:
  - cmd: bii build

test_script:
  - cmd: cd bin
  - cmd: dir
  - cmd: Dani_MTB_continuous-integration_main.exe

deploy_script:
  - cmd: bii user %block_user% -p %secured_passwd%
  - cmd: bii publish -r

environment:
  block_user:
    "Dani_MTB"
  secured_passwd:
    secure: Xs9AudM/J5BVLFyYfvrTOw==